In [1]:
#pip install pm4py
import importlib
import pm4py
from sklearn.preprocessing import LabelEncoder

In [1]:
#importlib.reload(readDataset)
import readDataset
log = readDataset.readData()

C:\Users\Loui\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pm4py\util\dt_parsing\parser.py:76: UserWarning: ISO8601 strings are not fully supported with strpfromiso for Python versions below 3.11
  warnings.warn(
C:\Users\Loui\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
parsing log, completed traces :: 100%|██████████| 31509/31509 [07:29<00:00, 70.10it/s]

In [10]:
no_time = log['time:timestamp'].isnull().any() or log['time:timestamp'].isna().any()
no_time

False

General Information on the dataset and check of requirements.

In [11]:
#importlib.reload(generalInfo)
import generalInfo
generalInfo.infos(log)

Requirements satisfied
['Action' 'org:resource' 'concept:name' 'EventOrigin' 'EventID'
 'lifecycle:transition' 'time:timestamp' 'case:LoanGoal'
 'case:ApplicationType' 'case:concept:name' 'case:RequestedAmount'
 'FirstWithdrawalAmount' 'NumberOfTerms' 'Accepted' 'MonthlyCost'
 'Selected' 'CreditScore' 'OfferedAmount' 'OfferID']

Delete all unfinished cases

In [14]:
#importlib.reload(finishedCases)
import finishedCases
finishedCasesLog = finishedCases.deleteUnfinishedCases(log)
finishedCasesLog.head()

Number of relevant (finished) cases:  31411
Number of unfinished cases:  98

,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,case:ApplicationType,case:concept:name,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15.304000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15.352000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15.774000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36.392000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36.403000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are 98 unfinished cases which are filtered out.

Number of Cases with multiple offers

In [19]:
#importlib.reload(analysisCases)
import analysisCases
analysisCases.analysis(finishedCasesLog)

Total amount of made offers: 42815
More than 1 offer: 8511
offer_0: 0
offer_1: 22900
offer_2: 6549
offer_3: 1337
offer_4: 438
offer_5: 125
offer_6: 29
offer_7: 16
offer_8: 12
offer_9: 3
offer_10: 2
More than 10 offers: 0

### Data Enhancement
Get the finished Cases and work with these for enhancement purposes

In [72]:
#importlib.reload(readDataset)
import readDataset
finishedCasesLog = readDataset.readfinishedLog()
finishedCasesLog.head()

,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,case:ApplicationType,case:concept:name,case:RequestedAmount,FirstWithdrawalAmount,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID
0,Created,User_1,A_Create Application,Application,Application_652823628,complete,2016-01-01 09:51:15.304000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,statechange,User_1,A_Submitted,Application,ApplState_1582051990,complete,2016-01-01 09:51:15.352000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Created,User_1,W_Handle leads,Workflow,Workitem_1298499574,schedule,2016-01-01 09:51:15.774000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Deleted,User_1,W_Handle leads,Workflow,Workitem_1673366067,withdraw,2016-01-01 09:52:36.392000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Created,User_1,W_Complete application,Workflow,Workitem_1493664571,schedule,2016-01-01 09:52:36.403000+00:00,Existing loan takeover,New credit,Application_652823628,20000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
importlib.reload(enhanceDataset)
import enhanceDataset
enhancedLog = enhanceDataset.enhancement(finishedCasesLog)
enhancedLog.head()

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,treatment,successful,treatmentSuccess
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0

### Deleting NaN

In [23]:
importlib.reload(readDataset)
import readDataset
log = readDataset.readEnhancedData()
log.head()

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,treatment,successful,treatmentSuccess
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,notTreated,0,0

In [25]:
#importlib.reload(fillNaN)
import fillNaN
filledLog = fillNaN.fillNaN(log)
filledLog.head()

/pfs/data5/home/ma/ma_ma/ma_mskiera/master-thesis/fillNaN.py:50: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  log['OfferID'].fillna(method='ffill', inplace=True)

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,NumberOfTerms,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,treatment,successful,treatmentSuccess
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,22.0,True,241.28,False,0.0,5000.0,Offer_410892064,notTreated,0,0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,22.0,True,241.28,False,0.0,5000.0,Offer_410892064,notTreated,0,0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,22.0,True,241.28,False,0.0,5000.0,Offer_410892064,notTreated,0,0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,22.0,True,241.28,False,0.0,5000.0,Offer_410892064,notTreated,0,0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,22.0,True,241.28,False,0.0,5000.0,Offer_410892064,notTreated,0,0

In [26]:
specific_case_df = filledLog[filledLog['case:concept:name'] == 'Application_1004601801']

# Display the relevant columns
columns_to_display = ['concept:name', 'OfferID', 'FirstWithdrawalAmount', 'NumberOfTerms', 'MonthlyCost', 'CreditScore', 'Accepted', 'Selected', 'OfferedAmount']
specific_case_df[columns_to_display]

,concept:name,OfferID,FirstWithdrawalAmount,NumberOfTerms,MonthlyCost,CreditScore,Accepted,Selected,OfferedAmount
2779,A_Create Application,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2780,A_Submitted,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2781,W_Handle leads,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2782,W_Handle leads,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2783,W_Complete application,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2784,A_Concept,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2785,A_Accepted,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2786,O_Create Offer,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2787,O_Created,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2788,O_Create Offer,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2789,O_Created,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2790,O_Sent (mail and online),Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2791,O_Sent (mail and online),Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2792,W_Complete application,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2793,W_Call after offers,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2794,W_Call after offers,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2795,A_Complete,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2796,W_Call after offers,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2797,W_Call after offers,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2798,W_Call after offers,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0
2799,O_Create Offer,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2800,O_Created,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2801,O_Sent (mail and online),Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2802,W_Call after offers,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2803,W_Validate application,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2804,W_Validate application,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2805,A_Validating,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2806,O_Returned,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2807,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2808,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2809,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2810,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2811,A_Incomplete,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2812,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2813,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2814,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2815,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2816,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2817,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2818,A_Validating,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2819,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2820,W_Validate application,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2821,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2822,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2823,A_Incomplete,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2824,O_Accepted,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2825,A_Pending,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2826,W_Call incomplete files,Offer_1446246189,15000.0,80.0,216.09,757.0,True,True,15000.0
2827,O_Cancelled,Offer_1132789743,15000.0,80.0,216.09,0.0,True,False,15000.0
2828,O_Cancelled,Offer_810209193,13500.0,72.0,217.92,0.0,True,False,13500.0

In [27]:
import pandas as pd
filledLog["time:timestamp"] = pd.to_datetime(filledLog["time:timestamp"], format='ISO8601')

In [28]:
import pm4py
filledLog.to_csv('bpi2017_filledLog.csv', index=False)
log_enhancedData = pm4py.convert_to_event_log(filledLog)
pm4py.write_xes(filledLog, 'bpi2017_filledLog.xes')

/pfs/data5/home/ma/ma_ma/ma_mskiera/master-thesis/thesis/lib/python3.9/site-packages/pm4py/utils.py:508: UserWarning: the EventLog class has been deprecated and will be removed in a future release.
  warnings.warn("the EventLog class has been deprecated and will be removed in a future release.")

exporting log, completed traces ::   0%|          | 0/31411 [00:00<?, ?it/s]

In [ ]:
filledLog['treatment'] = filledLog['treatment'].replace({'treated': 1, 'notTreated': 0}).astype('int64')
filledLog['treatmentSuccess'] = filledLog['treatmentSuccess'].replace({'Yes': 2, 'No': 1, '0': 0}).astype('int64')

In [ ]:
filledLog.rename(columns={'successful': 'caseSuccesful','treatment':'treatedCase' }, inplace=True)

Create column offerNumber

One can get per case the unique offerIDs and then set offerNumber 1-n accordingly.

In [ ]:
#before I had two seperate preprocessing files
df_og = filledLog

In [14]:
#offer_id_number_mappings = {}
for case in df_og['case:concept:name'].unique():
    # Get the rows corresponding to the current case
    offer_ids = df_og[df_og['case:concept:name'] == case]['OfferID'].unique()

    # Initialize a counter to assign unique numbers
    offer_id_number = 1

    # Assign unique numbers to each OfferID
    for offer_id in offer_ids:
        df_og.loc[df_og['OfferID'] == offer_id, 'offerNumber'] = offer_id_number
        #offer_id_number_mappings[case, offer_id] = offer_id_number
        offer_id_number += 1
df_og

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,Accepted,MonthlyCost,Selected,CreditScore,OfferedAmount,OfferID,treatedCase,successful,treatmentSuccess,offerNumber
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,True,241.28,False,0.0,5000.0,Offer_410892064,0,0,0,1.0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,True,241.28,False,0.0,5000.0,Offer_410892064,0,0,0,1.0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,True,241.28,False,0.0,5000.0,Offer_410892064,0,0,0,1.0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,True,241.28,False,0.0,5000.0,Offer_410892064,0,0,0,1.0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,True,241.28,False,0.0,5000.0,Offer_410892064,0,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198314,Application_999993812,1,Obtained,User_41,W_Call incomplete files,Workflow,Workitem_1102967432,resume,2016-10-20 08:19:28.812000+00:00,Caravan / Camper,...,True,349.13,True,877.0,30000.0,Offer_913122697,0,1,0,1.0
1198315,Application_999993812,1,Released,User_41,W_Call incomplete files,Workflow,Workitem_454743075,suspend,2016-10-20 08:21:59.667000+00:00,Caravan / Camper,...,True,349.13,True,877.0,30000.0,Offer_913122697,0,1,0,1.0
1198316,Application_999993812,1,statechange,User_68,O_Accepted,Offer,OfferState_1927291643,complete,2016-10-24 06:24:30.056000+00:00,Caravan / Camper,...,True,349.13,True,877.0,30000.0,Offer_913122697,0,1,0,1.0
1198317,Application_999993812,1,statechange,User_68,A_Pending,Application,ApplState_1253134444,complete,2016-10-24 06:24:30.059000+00:00,Caravan / Camper,...,True,349.13,True,877.0,30000.0,Offer_913122697,0,1,0,1.0
1198318,Application_999993812,1,Deleted,User_68,W_Call incomplete files,Workflow,Workitem_1302194036,ate_abort,2016-10-24 06:24:30.061000+00:00,Caravan / Camper,...,True,349.13,True,877.0,30000.0,Offer_913122697,0,1,0,1.0

In [4]:
df_og['offerSuccess'] = (df_og['caseSuccesful'] == 1) & (df_og['offerNumber'] == df_og['NumberOfOffers']).astype(int)
df_og['treatmentOffer'] = (df_og['offerNumber'] >= 2).astype(int)
df_og.head()

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,Selected,CreditScore,OfferedAmount,OfferID,treatedCase,caseSuccesful,treatmentSuccess,offerNumber,offerSuccess,treatmentOffer
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,False,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,False,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,False,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,False,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,False,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0

In [5]:
df_og["time:timestamp"] = pd.to_datetime(df_og["time:timestamp"], format='ISO8601')
df_og['timeApplication'] = df_og.groupby('case:concept:name')['time:timestamp'].transform(lambda x: x - x.min())
df_og['timeApplication'] = df_og['timeApplication'].dt.total_seconds()
df_og

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,CreditScore,OfferedAmount,OfferID,treatedCase,caseSuccesful,treatmentSuccess,offerNumber,offerSuccess,treatmentOffer,timeApplication
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.000
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.061
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.290
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0,66.613
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,0.0,5000.0,Offer_410892064,0,0,0,1.0,False,0,66.620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198314,Application_999993812,1,Obtained,User_41,W_Call incomplete files,Workflow,Workitem_1102967432,resume,2016-10-20 08:19:28.812000+00:00,Caravan / Camper,...,877.0,30000.0,Offer_913122697,0,1,0,1.0,True,0,1189344.713
1198315,Application_999993812,1,Released,User_41,W_Call incomplete files,Workflow,Workitem_454743075,suspend,2016-10-20 08:21:59.667000+00:00,Caravan / Camper,...,877.0,30000.0,Offer_913122697,0,1,0,1.0,True,0,1189495.568
1198316,Application_999993812,1,statechange,User_68,O_Accepted,Offer,OfferState_1927291643,complete,2016-10-24 06:24:30.056000+00:00,Caravan / Camper,...,877.0,30000.0,Offer_913122697,0,1,0,1.0,True,0,1528045.957
1198317,Application_999993812,1,statechange,User_68,A_Pending,Application,ApplState_1253134444,complete,2016-10-24 06:24:30.059000+00:00,Caravan / Camper,...,877.0,30000.0,Offer_913122697,0,1,0,1.0,True,0,1528045.960
1198318,Application_999993812,1,Deleted,User_68,W_Call incomplete files,Workflow,Workitem_1302194036,ate_abort,2016-10-24 06:24:30.061000+00:00,Caravan / Camper,...,877.0,30000.0,Offer_913122697,0,1,0,1.0,True,0,1528045.962

In [7]:
#A_Create Application
def get_weekday(timestamp):
    return timestamp.weekday()

# Apply the function to create the new column 'weekdayApplication'
df_og['weekdayApplication'] = df_og[df_og['concept:name'] == 'A_Create Application']['time:timestamp'].apply(get_weekday)

# Forward fill the 'weekdayApplication' column to fill the NaN values for other rows in the same case
df_og['weekdayApplication'] = df_og.groupby('case:concept:name')['weekdayApplication'].transform(lambda x: x.ffill().bfill())
df_og.head()

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,EventID,lifecycle:transition,time:timestamp,case:LoanGoal,...,OfferedAmount,OfferID,treatedCase,caseSuccesful,treatmentSuccess,offerNumber,offerSuccess,treatmentOffer,timeApplication,weekdayApplication
0,Application_1000086665,1,Created,User_1,A_Create Application,Application,Application_1000086665,complete,2016-08-03 15:57:21.673000+00:00,"Other, see explanation",...,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.000,2.0
1,Application_1000086665,1,statechange,User_1,A_Submitted,Application,ApplState_161925113,complete,2016-08-03 15:57:21.734000+00:00,"Other, see explanation",...,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.061,2.0
2,Application_1000086665,1,Created,User_1,W_Handle leads,Workflow,Workitem_747707399,schedule,2016-08-03 15:57:21.963000+00:00,"Other, see explanation",...,5000.0,Offer_410892064,0,0,0,1.0,False,0,0.290,2.0
3,Application_1000086665,1,Deleted,User_1,W_Handle leads,Workflow,Workitem_1030261128,withdraw,2016-08-03 15:58:28.286000+00:00,"Other, see explanation",...,5000.0,Offer_410892064,0,0,0,1.0,False,0,66.613,2.0
4,Application_1000086665,1,Created,User_1,W_Complete application,Workflow,Workitem_1127124826,schedule,2016-08-03 15:58:28.293000+00:00,"Other, see explanation",...,5000.0,Offer_410892064,0,0,0,1.0,False,0,66.620,2.0

In [17]:
import pm4py
log_final = pm4py.convert_to_event_log(df_og)
pm4py.write_xes(log_final, 'bpi2017_final_log.xes')

/pfs/data5/home/ma/ma_ma/ma_mskiera/thesis/lib/python3.9/site-packages/pm4py/utils.py:538: UserWarning: the EventLog class has been deprecated and will be removed in a future release.
  warnings.warn("the EventLog class has been deprecated and will be removed in a future release.")

exporting log, completed traces ::   0%|          | 0/31411 [00:00<?, ?it/s]

In [ ]:
df_processed = df_og.drop(columns=['EventID', 'OfferID'])

In [13]:
non_numeric_columns = list(df_processed.select_dtypes(exclude=[np.number]).columns)

for col in non_numeric_columns:
    df_processed[col] = LabelEncoder().fit_transform(df_processed[col])

df_processed_float = df_processed.astype('float32')
df_processed_float.head(5)

,case:concept:name,NumberOfOffers,Action,org:resource,concept:name,EventOrigin,lifecycle:transition,time:timestamp,case:LoanGoal,case:ApplicationType,...,CreditScore,OfferedAmount,treatedCase,caseSuccesful,treatmentSuccess,offerNumber,offerSuccess,treatmentOffer,timeApplication,weekdayApplication
0,0.0,1.0,0.0,0.0,4.0,0.0,1.0,651433.0,10.0,1.0,...,0.0,5000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,2.0
1,0.0,1.0,4.0,0.0,8.0,0.0,1.0,651434.0,10.0,1.0,...,0.0,5000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.061000,2.0
2,0.0,1.0,0.0,0.0,22.0,2.0,3.0,651435.0,10.0,1.0,...,0.0,5000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.290000,2.0
3,0.0,1.0,1.0,0.0,22.0,2.0,6.0,651437.0,10.0,1.0,...,0.0,5000.0,0.0,0.0,0.0,1.0,0.0,0.0,66.612999,2.0
4,0.0,1.0,0.0,0.0,21.0,2.0,3.0,651438.0,10.0,1.0,...,0.0,5000.0,0.0,0.0,0.0,1.0,0.0,0.0,66.620003,2.0

In [ ]:
df_processed_float.to_csv('bpi2017_final.csv', index=False)